### PR TITLE
Update versions of actions dependencies

### PR DESCRIPTION
**Pull request by jcollins1983**
Remove test PyPI and update action versions in step with test.yml

### CODE REVIEW

**Comment by clint-lawrence** [comment]
I assume you're happy to just close this now that test pypi is back up?

**Comment by jcollins1983** [comment]
We could, but do we really need the test PyPI in the workflow? I suppose if something fails there, we won't be forced to up rev on the real PyPI. If we don't delete the test PyPI, wouldn't we still want to update the actions?

**Comment by pazzarpj** [comment]
I guess I didn't really get it sorted in the beginning.  But the intention
of the test pypi would be to check that all the artifacts are there by say
doing a fresh pip install from test pypi and running the tests.

**Comment by jcollins1983** [comment]
Reinstated test PyPI, only changes now are to the action versions to be inline with those in test.yml

**Pull request merged**
