### PR TITLE
Add additional script to log integration test

### PR DESCRIPTION
**Pull request by clint-lawrence**

### CODE REVIEW

**Comment by clint-lawrence** [comment]
@pazzarpj, I just remembered the CI doesn't run of forked repos. Should I push the same branch to the main repo?

**Comment by pazzarpj** [comment]
@clint-lawrence I fixed it so it does work on forks. The bug is still there but I don't publish the wheel.

**Comment by pazzarpj** [comment]
Failing test_basichierachy[None-test_test-None-10] on python 3.7 only
At index 8 diff: ['Test 1.1', 'exception', "AssertionError('Exception in the test test',)"] != ['Test 1.1', 'exception', "AssertionError('Exception in the test test')"]

**Comment by pazzarpj** [comment]
https://docs.python.org/3/whatsnew/3.7.html

repr for BaseException has changed to not include the trailing comma. Most exceptions are affected by this change. (Contributed by Serhiy Storchaka in bpo-30399.)

**Comment by pazzarpj** [comment]
Fixed that. Can you review if that's the way you want the issue resolved?

**Comment by pazzarpj** [comment]
After that, happy to merge

**Comment by clint-lawrence** [comment]
It exposes the fragility of these tests a little. Although there shouldn't be too many places where we're at the mercy of external behaviour in the log, so hopefully similar things to bite us much.

Given that the repr isn't that useful a better solution long term might be to not use the repr, just define the message we want to log and the create a separate error log which a full traceback. But other than those random thoughts, your fix is fine.

**Pull request merged**
