### PR TITLE
Move examples out of the package and update readme

### PR DESCRIPTION
**Pull request by clint-lawrence**
This came up somewhere in the threads discussion the `VirtualMux` related changes.

### CODE REVIEW

**Comment by clint-lawrence** [comment]
@daniel-montanari tagged you for require, because I think you suggested this? or at least we discussed it.

**Review by daniel-montanari — CHANGES_REQUESTED** [review]
Looks good, can we remove the examples folder from `mypy.ini` exclusions now please.
[mypy.ini](https://github.com/PyFixate/Fixate/blob/move-examples/mypy.ini)

I believe the rules on the example files at the bottom are also no longer required.

**Comment by clint-lawrence** [comment]
> I believe the rules on the example files at the bottom are also no longer required.

Should be good now.

**Review by daniel-montanari — APPROVED** [review]
Looks good

**Pull request merged**
